services:
  backend:
    image: nhutkhang/mern-backend:1.0
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - ./mern-demo/.env
    networks:
      - mern-network

  frontend:
    image: nhutkhang/mern-frontend:1.0
    container_name: mern-frontend-hub
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
