services:
  backend:
    build:
      context: ./mern-demo/server
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - ./mern-demo/.env
    networks:
      - mern-network

  frontend:
    build:
      context: ./mern-demo/client
    container_name: mern-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
